// flow-typed signature: 5aa2f10eccf0d346fac8b182fc4e7c76
// flow-typed version: <<STUB>>/@webpack-blocks/dev-server2_v^0.4.0/flow_v0.39.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@webpack-blocks/dev-server2'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module '@webpack-blocks/dev-server2' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module '@webpack-blocks/dev-server2/index' {
  declare module.exports: $Exports<'@webpack-blocks/dev-server2'>;
}
declare module '@webpack-blocks/dev-server2/index.js' {
  declare module.exports: $Exports<'@webpack-blocks/dev-server2'>;
}
